require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'vendor/**/*'
  TargetRubyVersion: 3.0.0

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 15

Layout/LineLength:
  Max: 120

Metrics/BlockNesting:
  Max: 5

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 35

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 20

Naming/FileName:
  Enabled: false

# TODO: investigate proper upgrade path and remove
Lint/UriEscapeUnescape:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# make sure Time is used over DateTime
Style/DateTime:
  Enabled: true

Style/FormatStringToken:
  Enabled: false

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - staging
    - test

# TODO: investigate proper upgrade path and remove
Rails/SkipsModelValidations:
  Enabled: false

# TODO: investigate proper upgrade path and remove
Rails/Output:
  Enabled: false

# TODO: investigate proper upgrade path and remove
Rails/HasManyOrHasOneDependent:
  Enabled: false

# TODO: re-enable. Disabled because of this bug
# https://github.com/rubocop-hq/rubocop-rails/commit/bb266fd942f756e75209cde0430162659e216e01
Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/CaseLikeIf:
  Enabled: false

Lint/FloatComparison:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false

Rails/ActionOrder:
  ExpectedOrder:
    - index
    - show
    - new
    - create
    - edit
    - update
    - destroy